[[redirects]]
from = "/*"
to = "https://social-dances.netlify.app/index.html"
status = 200
force = true
headers = {X-From = "Netlify"}
[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"